### ISSUE TITLE
websocket doesn't seems to work with recent clash for android/magisk, openclash

### ISSUE THREAD

**Issue by samlux04** [alanbobs999/TopFreeProxies#50]
This won't work
```yaml
- name: 🇺🇸US-208.98.48.2-00
  server: iesei1ei.com
  port: 443
  type: vmess
  uuid: aba50dd4-5484-3b05-b14a-4661caf862d5
  alterId: 4
  cipher: auto
  skip-cert-vertify: true
  network: ws
  ws-path: /ws
  tls: true
  ws-headers:
    Host: iesei1ei.com
```

Edited to this works
```yaml
- name: 🇺🇸US-208.98.48.2-00
  server: iesei1ei.com
  port: 443
  type: vmess
  uuid: aba50dd4-5484-3b05-b14a-4661caf862d5
  alterId: 4
  cipher: auto
  skip-cert-vertify: true
  network: ws
  tls: true
  ws-opts:
    path: /ws
    headers:
      Host: iesei1ei.com
  udp: true
```
Also added udp.
